# Generated by Django 3.2.5 on 2024-06-25 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
